#!/bin/bash

# Turn on extended globbing and programmable completion
shopt -s extglob progcomp

# If a glob doesn't match anything, just return nothing; don't try to interpret it literally
shopt -s nullglob

banner()
{
    echo "----------------------------------------------------------------"
    echo "$@"
    echo "----------------------------------------------------------------"
    echo
}

copy_to_home()
{
    for f in $PLUGIN_DIR/dotfiles/* $PLUGIN_DIR/dotfiles/.[^.]*; do
        cp -prv $f ~
    done
}

[ -n "$MACINSTALL_PLUGINS_DIR" ] || MACINSTALL_PLUGINS_DIR=scripts.d

if [[ -d $MACINSTALL_PLUGINS_DIR && -r $MACINSTALL_PLUGINS_DIR && -x $MACINSTALL_PLUGINS_DIR ]]; then
    for i in $(LC_ALL=C command ls "$MACINSTALL_PLUGINS_DIR"); do
        i=$MACINSTALL_PLUGINS_DIR/$i
        if [[ ${i##*/} == @(*~|*.bak|*.swp|\#*\#|*.dpkg*|*.rpm@(orig|new|save)|Makefile*) || ! -r $i ]]; then
            continue
        fi
        if [[ -f $i ]]; then
            banner "BEGIN executing: $i"
            . "$i"
            echo
            banner "END executing: $i"
        elif [[ -d $i ]]; then
            PLUGIN_DIR=$i
            banner "BEGIN Dir: $PLUGIN_DIR"
            if [[ -f $i/init.sh ]]; then
                SCRIPT=$i/init.sh
                . "$SCRIPT"
            else
                copy_to_home
            fi
            echo
            banner "END Dir: $PLUGIN_DIR"
        fi
    done
fi

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
